repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: Format with rustfmt
      - id: cargo-check
        name: Check with cargo
      - id: clippy
        name: Lint with clippy
        args: ['--', '-D', 'warnings']
